"""
Passive Agent Handler — Tool Definitions

Declares the tool capabilities exposed by the passive assistant agent.
All actual responses are generated by the configured LLM via app.py.
"""

from __future__ import annotations

from typing import Any

TOOL_DEFINITIONS = {
    "code_generate": {
        "name": "code_generate",
        "description": "根据自然语言描述生成代码",
        "parameters": {"language": "string", "description": "string"},
    },
    "code_review": {
        "name": "code_review",
        "description": "分析代码质量并给出改进建议",
        "parameters": {"code": "string", "language": "string"},
    },
    "text_write": {
        "name": "text_write",
        "description": "撰写技术文档或文章",
        "parameters": {"topic": "string", "style": "string"},
    },
    "text_summarize": {
        "name": "text_summarize",
        "description": "对长文本进行精炼摘要",
        "parameters": {"text": "string", "max_length": "integer"},
    },
    "format_convert": {
        "name": "format_convert",
        "description": "在不同格式间转换内容",
        "parameters": {"content": "string", "from_format": "string", "to_format": "string"},
    },
}


def get_tool_list() -> list[dict[str, Any]]:
    return list(TOOL_DEFINITIONS.values())
